// Function to generate random price between 20000 to 20000
function generateRandomPrice() {
  return Math.floor(Math.random() * (2000000 - 200000 + 1)) + 200000
}
function generateRandomCount() {
  return Math.floor(Math.random() * (20 - 10 + 1)) + 10
}

// Array of tables for dashboard sample on homepage
export const POOL_TABLE_BAR = [
  {
    name: "Table 1",
    total: generateRandomPrice(),
    count: generateRandomCount(),
  },
  {
    name: "Table 2",
    total: generateRandomPrice(),
    count: generateRandomCount(),
  },
  {
    name: "Table 3",
    total: generateRandomPrice(),
    count: generateRandomCount(),
  },
  {
    name: "Table 4",
    total: generateRandomPrice(),
    count: generateRandomCount(),
  },
  {
    name: "Table 5",
    total: generateRandomPrice(),
    count: generateRandomCount(),
  },
  {
    name: "Table 6",
    total: generateRandomPrice(),
    count: generateRandomCount(),
  },
]

export const sampleDiscountList = [
  { name: "0%", value: 0.0 },
  { name: "5%", value: 0.05 },
  { name: "10%", value: 0.1 },
  { name: "15%", value: 0.15 },
  { name: "20%", value: 0.2 },
]

export const sampleTaxList = [
  { name: "0%", value: 0.0 },
  { name: "6%", value: 0.05 },
  { name: "11%", value: 0.11, isDefaultValue: true },
  { name: "21%", value: 0.21 },
]

export const samplePacketList = [
  {
    name: "reguler",
    rate: "MINUTE",
    cost: 666.67,
    description: "paket per menit",
  },
  {
    name: "free",
    rate: "MINUTE",
    cost: 1,
    description: "free rate minute",
  },
  {
    name: "reguler",
    rate: "HOUR",
    cost: 40000,
    description: "paket per jam",
  },
  {
    name: "promo",
    rate: "HOUR",
    cost: 35000,
    description: "paket promo",
  },
  {
    name: "student",
    rate: "HOUR",
    cost: 30000,
    description: "paket student",
  },
  {
    name: "free",
    rate: "HOUR",
    cost: 1,
    description: "free rate hourly",
  },
]

const food_category_ID = "clxg7arm50000q0b4xsmi0ypy"
const drink_category_ID = "clxg7b3oz0001q0b4sr9hts02"
const others_category_ID = "clxg7bne40002q0b451iydw0p"
const unit_of_measure_ID = "clyfnkg4u000qz0eihg5l80a1"

export const sampleProductList = [
  {
    name: "a mild merah",
    costPrice: 45000,
    salePrice: 55000,
    status: "enabled",
    categoryId: others_category_ID,
  },
  {
    name: "americano hot",
    costPrice: 22000,
    salePrice: 27000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "banana ice coffee",
    costPrice: 33000,
    salePrice: 38000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "beef thai salad",
    costPrice: 50000,
    salePrice: 55000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "beef thai style",
    costPrice: 46000,
    salePrice: 51000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "cafe latte hot",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "calamary ring",
    costPrice: 34000,
    salePrice: 39000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "capcay ayam kuah",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "cappuccino hot",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "caramel latte frape",
    costPrice: 36000,
    salePrice: 41000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "caramel latte hot",
    costPrice: 33000,
    salePrice: 38000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "chicken gyoza",
    costPrice: 35000,
    salePrice: 40000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "chicken katsu curry",
    costPrice: 50000,
    salePrice: 55000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "chicken steak",
    costPrice: 55000,
    salePrice: 60000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "chicken thai style",
    costPrice: 50000,
    salePrice: 55000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "chicken wings",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "choco frape",
    costPrice: 36000,
    salePrice: 41000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "chocolate hot",
    costPrice: 33000,
    salePrice: 38000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "cireng",
    costPrice: 24000,
    salePrice: 29000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "coca cola",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "coffee espresso",
    costPrice: 12000,
    salePrice: 17000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "fanta",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "french fries",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "french mentai",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "fuyung hai ayam",
    costPrice: 43000,
    salePrice: 48000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "hazelnut latte frape",
    costPrice: 36000,
    salePrice: 41000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "hazzelnut latte hot",
    costPrice: 32000,
    salePrice: 37000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice americano",
    costPrice: 27000,
    salePrice: 32000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice berry latte",
    costPrice: 33000,
    salePrice: 38000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice cappuccino",
    costPrice: 29000,
    salePrice: 34000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice caramel latte",
    costPrice: 34000,
    salePrice: 39000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice chocolate",
    costPrice: 32000,
    salePrice: 37000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice coffee latte",
    costPrice: 27000,
    salePrice: 35000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice coffee pandan",
    costPrice: 33000,
    salePrice: 38000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice latte cocount",
    costPrice: 33000,
    salePrice: 38000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice lemon tea",
    costPrice: 23000,
    salePrice: 28000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice lychee tea",
    costPrice: 28000,
    salePrice: 33000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice mocha",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice sweet tea",
    costPrice: 17000,
    salePrice: 22000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "ice vanilla latte",
    costPrice: 33000,
    salePrice: 38000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "jamur enoki crispy",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "juice avocado",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "juice mango",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "juice melon",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "juice orange",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "juice strawberry",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "kampoeng fried noodle",
    costPrice: 38000,
    salePrice: 43000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "katsu salad",
    costPrice: 47000,
    salePrice: 52000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "king mango",
    costPrice: 34000,
    salePrice: 39000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "kwetiau ati ampela",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "kwetiau goreng ayam",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "marlboro merah",
    costPrice: 45000,
    salePrice: 55000,
    status: "enabled",
    categoryId: others_category_ID,
  },
  {
    name: "marlboro putih",
    costPrice: 45000,
    salePrice: 55000,
    status: "enabled",
    categoryId: others_category_ID,
  },
  {
    name: "mineral water",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "mocha frape",
    costPrice: 36000,
    salePrice: 41000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "marlboro ice blast",
    costPrice: 45000,
    salePrice: 55000,
    status: "enabled",
    categoryId: others_category_ID,
  },
  {
    name: "nachos",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "nasi goreng ati ampela",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "nasi goreng ikan asin",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "nasi goreng kornet",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "nasi goreng sosis",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "peach tea",
    costPrice: 28000,
    salePrice: 33000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "pocari sweat",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "fried rice",
    costPrice: 43000,
    salePrice: 48000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "spaghetti aglio olio tuna",
    costPrice: 60000,
    salePrice: 65000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "spaghetti bolognaise",
    costPrice: 60000,
    salePrice: 65000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "spaghetti carbonara",
    costPrice: 60000,
    salePrice: 65000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "sprite",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "strawberry smoothies",
    costPrice: 34000,
    salePrice: 39000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "strawberry tea",
    costPrice: 28000,
    salePrice: 33000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "truffle parmesan cheese",
    costPrice: 33000,
    salePrice: 38000,
    status: "enabled",
    categoryId: food_category_ID,
  },
  {
    name: "vanila ice blend",
    costPrice: 36000,
    salePrice: 41000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
  {
    name: "vanilla latte hot",
    costPrice: 32000,
    salePrice: 37000,
    status: "enabled",
    categoryId: drink_category_ID,
  },
]

// unitOfMeasureId only for sample trial products
export const sampleTrialProductList = [
  {
    name: "mineral water",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
    unitOfMeasureId: unit_of_measure_ID,
  },
  {
    name: "cappuccino hot",
    costPrice: 25000,
    salePrice: 30000,
    status: "enabled",
    categoryId: drink_category_ID,
    unitOfMeasureId: unit_of_measure_ID,
  },
  {
    name: "nasi goreng kornet",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
    unitOfMeasureId: unit_of_measure_ID,
  },
  {
    name: "chicken wings",
    costPrice: 30000,
    salePrice: 35000,
    status: "enabled",
    categoryId: food_category_ID,
    unitOfMeasureId: unit_of_measure_ID,
  },
  {
    name: "a mild merah",
    costPrice: 45000,
    salePrice: 55000,
    status: "enabled",
    categoryId: others_category_ID,
    unitOfMeasureId: unit_of_measure_ID,
  },
  {
    name: "marlboro putih",
    costPrice: 45000,
    salePrice: 55000,
    status: "enabled",
    categoryId: others_category_ID,
    unitOfMeasureId: unit_of_measure_ID,
  },
]
