export const countries = [
  {
    code: "BN",
    country: "Brunei Darussalam",
    currency: "BND",
    locale: "ms-BN",
    flag: "https://flagcdn.com/bn.svg",
  },
  {
    code: "KH",
    country: "Cambodia",
    currency: "KHR",
    locale: "km-KH",
    flag: "https://flagcdn.com/kh.svg",
  },
  {
    code: "ID",
    country: "Indonesia",
    currency: "IDR",
    locale: "id-ID",
    flag: "https://flagcdn.com/id.svg",
  },
  {
    code: "LA",
    country: "Lao PDR (Laos)",
    currency: "LAK",
    locale: "lo-LA",
    flag: "https://flagcdn.com/la.svg",
  },
  {
    code: "MY",
    country: "Malaysia",
    currency: "MYR",
    locale: "ms-MY",
    flag: "https://flagcdn.com/my.svg",
  },
  {
    code: "MM",
    country: "Myanmar",
    currency: "MMK",
    locale: "my-MM",
    flag: "https://flagcdn.com/mm.svg",
  },
  {
    code: "PH",
    country: "Philippines",
    currency: "PHP",
    locale: "en-PH",
    flag: "https://flagcdn.com/ph.svg",
  },
  {
    code: "SG",
    country: "Singapore",
    currency: "SGD",
    locale: "en-SG",
    flag: "https://flagcdn.com/sg.svg",
  },
  {
    code: "TH",
    country: "Thailand",
    currency: "THB",
    locale: "th-TH",
    flag: "https://flagcdn.com/th.svg",
  },
  {
    code: "VN",
    country: "Vietnam",
    currency: "VND",
    locale: "vi-VN",
    flag: "https://flagcdn.com/vn.svg",
  },
]
